using System.IO;
using System.Text;

namespace Yoji.U3DAILinker.Agents
{
    /// <summary>
    /// Writes the single u3d-ai-linker managed block into a Markdown file.
    /// Content outside the block is preserved byte-for-byte (after newline
    /// normalization to \n). Corrupt or duplicated markers abort without writing.
    /// </summary>
    public static class ManagedBlockWriter
    {
        public const string StartMarker = "<!-- u3d-ai-linker:start -->";
        public const string EndMarker = "<!-- u3d-ai-linker:end -->";
        private const string Preamble = "Generated by U3D Dev Tools AI. Do not edit this block.";

        /// <summary>
        /// Inserts or updates the managed block. <paramref name="body"/> is the merged
        /// fragment text (without markers); pass an empty string to write an empty block.
        /// </summary>
        public static BlockWriteResult Write(string filePath, string body)
        {
            string existing = File.Exists(filePath)
                ? File.ReadAllText(filePath).Replace("\r\n", "\n")
                : null;

            int startCount = CountOccurrences(existing ?? string.Empty, StartMarker);
            int endCount = CountOccurrences(existing ?? string.Empty, EndMarker);

            if (startCount > 1 || endCount > 1)
                return BlockWriteResult.Conflict("Duplicate u3d-ai-linker markers found.");
            if (startCount != endCount)
                return BlockWriteResult.Conflict("Unbalanced u3d-ai-linker markers found.");

            string block = BuildBlock(body);

            if (startCount == 0)
            {
                // No managed block yet: create file or append to user content.
                string head = existing ?? string.Empty;
                string newText = head.Length == 0
                    ? block + "\n"
                    : EnsureTrailingNewline(head) + block + "\n";
                if (existing != null && existing == newText)
                    return BlockWriteResult.Unchanged();
                AtomicTextFile.Write(filePath, newText);
                return BlockWriteResult.Written();
            }

            int startIdx = existing.IndexOf(StartMarker, System.StringComparison.Ordinal);
            int endIdx = existing.IndexOf(EndMarker, System.StringComparison.Ordinal);
            if (endIdx < startIdx)
                return BlockWriteResult.Conflict("u3d-ai-linker end marker precedes start marker.");

            int endLineEnd = endIdx + EndMarker.Length;
            string before = existing.Substring(0, startIdx);
            string after = existing.Substring(endLineEnd);
            string replaced = before + block + after;

            if (replaced == existing)
                return BlockWriteResult.Unchanged();

            AtomicTextFile.Write(filePath, replaced);
            return BlockWriteResult.Written();
        }

        private static string BuildBlock(string body)
        {
            var sb = new StringBuilder();
            sb.Append(StartMarker).Append('\n');
            sb.Append(Preamble).Append('\n');
            if (!string.IsNullOrEmpty(body))
                sb.Append(body.Replace("\r\n", "\n").TrimEnd('\n')).Append('\n');
            sb.Append(EndMarker);
            return sb.ToString();
        }

        private static string EnsureTrailingNewline(string s)
            => s.EndsWith("\n") ? s : s + "\n";

        private static int CountOccurrences(string haystack, string needle)
        {
            int count = 0, i = 0;
            while ((i = haystack.IndexOf(needle, i, System.StringComparison.Ordinal)) >= 0)
            {
                count++;
                i += needle.Length;
            }
            return count;
        }
    }
}
